### ISSUE TITLE
Consider switching to less instead of sass as style language

### ISSUE THREAD

**Issue by ptolomeus** [desto-git/scrollbar.js#4]
Comparing to dependency graph *less* seems to be more "lightweight" than *sass*

http://npm.broofa.com/?q=sass (147 deps)

http://npm.broofa.com/?q=less (58 deps)

**Comment by desto-git** [comment]
Since a CSS preprocessor is a devDependency and as such not shipped with the final product, the dependency tree should not carry much weight in this decision. This project is small enough that this should not matter.

Additionally, the point of a styleable scrollbar is to actually customize it. The basic stylesheet supplied by this project is just a guide on how to add enough styles to make it resemble a scrollbar, but by no means a visually pleasing one.

Maybe I should ditch the preprocessor altogether, since there's no real benefit in using one with the small stylesheet this project has. Even after adding more presets as per your other request ;)
Especially as it is not minified in the dist folder, because again it's just a template.

Initially the thought was that changing the prefix might be easier this way, but as I see now this is void if the user is using a different preprocessor. Pretty much any text editor has a replace mechanism fit for this task, so no need to put more technologies on top.
